# NumPy Exercises

In [1]:
import numpy as np

**1.** Write a NumPy program to test whether none of the elements of a given array is zero.

In [2]:
x = np.array([1, 2, 3, 4])

print("Original array:")
print(x)
print("Test if none of the elements of the array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the array is zero:
True


In [3]:
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the array is zero:")
print(np.all(x))

Original array:
[0 1 2 3]
Test if none of the elements of the array is zero:
False


**2.** Write a NumPy program to test element-wise for NaN of a given array

In [4]:
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


**3.** Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [5]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


**4.** Write a NumPy program to save a given array to a binary file.

In [6]:
import os

a = np.arange(20)
np.save('temp_arra.npy', a)

print("Check if 'temp_arra.npy' exists or not?")
if os.path.exists('temp_arra.npy'):
    x2 = np.load('temp_arra.npy')
    print(np.array_equal(a, x2))

Check if 'temp_arra.npy' exists or not?
True


**5.** Write a NumPy program to convert a given array into a list and then convert it into a list again.

In [7]:
a = [[1, 2], [3, 4]]
x = np.array(a)
a2 = x.tolist()
print(a == a2)

True


**6.** Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [8]:
x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[6 8 0 6 0]


**7.** Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [9]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


**8.** Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [10]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


**9.** Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

Original array:

`[[ 0 10 20]
[20 30 40]]`

Values bigger than 10: 

`[20 20 30 40]`

Their indices are 

`(array([0, 1, 1, 1]), array([2, 0, 1, 2]))`

In [11]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


**10.** Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values. Go to the editor
Expected Output:

Original array:

`[[ 1. 2. 3.]
[ 4. 5. nan]
[ 7. 8. 9.]
[ 1. 0. 1.]]`

Remove all non-numeric elements of the said array

`[[ 1. 2. 3.]
[ 7. 8. 9.]
[ 1. 0. 1.]]`

In [12]:
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])

print("Original array:")
print(x)
print("Remove all non-numeric elements of the said array")
print(x[~np.isnan(x).any(axis=1)])

Original array:
[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
Remove all non-numeric elements of the said array
[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]
